### ISSUE TITLE
Infinite loops when Scarecrows already exist

### ISSUE THREAD

**Issue by wroxxor** [StewGoin/platstuff#1]
When the script needs to advance the room number, the section that adds one to the room variable, returns back to the section that adds to the room variable again instead of having the player go to the next room. This causes an Infinite loop where the room number keeps increasing, since the player never traverses to the next room, the if condition is satisfied and the room number is increased once more. 

I have change my scripts localy for each section so that instead of  going to the build label again, it goes instead to the start label and thus moves the player to the next room before checking the room for a scarecrow again:

OLD:
right_start:
gosub go_room %right_room

right_build:
if matchre("$roomobjs", "scarecrow") then
{
    evalmath right_room (%right_room + 1)
    goto right_build
}

NEW:
right_start:
gosub go_room %right_room

right_build:
if matchre("$roomobjs", "scarecrow") then
{
    evalmath right_room (%right_room + 1)
    goto right_start
}

**Comment by StewGoin** [comment]
Yep, infinite loops suck. Good find.
